services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: "always"
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=market
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: "always"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trading
    ports:
      - "5433:5432" # map host 5433 to container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: "always"

volumes:
  timescaledb_data:
  postgres_data:
